CREATE TABLE MEMBER(
    ID BIGINT generated by default as identity,
    EMAIL VARCHAR2(255),
    NAME VARCHAR2(255),
    NICK VARCHAR2(255),
    PWD VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    PRIMARY KEY(ID)
);
CREATE  TABLE CONTENT(
    IDX BIGINT GENERATED BY DEFAULT AS IDENTITY,
    IMG VARCHAR2(255),
    TITLE VARCHAR2(255),
    CONTENT VARCHAR2(255),
    M_ID NUMBER,
    REG_DATETIME DATE,
    MOD_DATETIME DATE,
    PRIMARY KEY(IDX)
)


---- 핵심 로직 실행되는데 소요되는 시간 측정
--회원가입, 회원 조회에 시간을 측정하는 기능은 핵심 관심 사항이 아니다.
--시간을 측정하는 로직과 핵심 비즈니스의 로직이 섞여서 유지보수가 어렵다.
--시간을 측정하는 로직을 별도의 공통 로직으로 만들기 매우 어렵다.
--시간을 측정하는 로직을 변경할 때 모든 로직을 찾아가면서 변경해야 한다.